//! Record & Replay schema: [`RecordedStep`] and [`Recording`].
//!
//! A [`Recording`] is an ordered sequence of [`RecordedStep`]s captured during a
//! browser session. Each step stores the action intent, the engine action name,
//! serialized arguments, an optional stable CSS/aria selector for the target
//! element, and the page URL at the time of the action. Recordings round-trip
//! through JSON (serde) and **never** contain resolved secret values — only
//! `secret:NAME` tokens (see Task 2 invariant).

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// A single recorded browser action step.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RecordedStep {
    /// Human-readable intent / description of the action (e.g. "click the Submit button").
    pub intent: String,
    /// The engine action name (e.g. "click", "type", "navigate").
    pub action: String,
    /// Serialized action arguments (a JSON object with the action-specific params).
    /// For secret-typed inputs, contains `"secret:NAME"` token — NEVER the resolved value.
    pub args: Value,
    /// A stable selector for the target element (generated by the vendored
    /// selectorGenerator). `None` for actions that don't target an element
    /// (navigate, back, forward, reload, etc.).
    pub selector: Option<String>,
    /// The page URL at the time this step was recorded.
    pub url: String,
}

/// **Security invariant**: the `secret:NAME` token prefix. Step construction MUST
/// copy this token verbatim into `args`; the resolved plaintext value NEVER enters
/// a recording. This constant is shared with the facade's `SECRET_PREFIX`.
pub const SECRET_PREFIX: &str = "secret:";

impl RecordedStep {
    /// Construct a step from the **raw tool input** (pre-resolution).
    ///
    /// **SECURITY**: `input` is the *original* tool input that contains `secret:NAME`
    /// tokens (not resolved values). The facade MUST call this with the input *before*
    /// secret resolution — this is the structural guarantee that plaintext never enters
    /// a recording.
    pub fn from_action(
        action: &str,
        input: &Value,
        selector: Option<String>,
        url: String,
    ) -> Self {
        Self {
            intent: describe_action(action, input),
            action: action.to_string(),
            args: sanitize_args(input),
            selector,
            url,
        }
    }
}

/// Build a human-readable intent from the action + input (best-effort).
fn describe_action(action: &str, input: &Value) -> String {
    match action {
        "click" => {
            let r = input.get("ref").and_then(|v| v.as_str()).unwrap_or("?");
            format!("click [ref={r}]")
        }
        "type" => {
            let r = input.get("ref").and_then(|v| v.as_str()).unwrap_or("?");
            let text = input.get("text").and_then(|v| v.as_str()).unwrap_or("");
            if text.starts_with(SECRET_PREFIX) {
                format!("type secret into [ref={r}]")
            } else {
                format!("type into [ref={r}]")
            }
        }
        "navigate" => {
            let url = input.get("url").and_then(|v| v.as_str()).unwrap_or("?");
            format!("navigate to {url}")
        }
        other => other.to_string(),
    }
}

/// Sanitize args for recording: strip internal sentinel keys (like
/// `__out_of_band_confirmed`) but preserve everything else — including
/// `secret:NAME` tokens (they are safe to store; plaintext is not).
fn sanitize_args(input: &Value) -> Value {
    match input {
        Value::Object(map) => {
            let mut out = serde_json::Map::new();
            for (k, v) in map {
                // Strip internal protocol keys (double-underscore prefix).
                if k.starts_with("__") {
                    continue;
                }
                // Strip the "action" key (redundant with RecordedStep::action).
                if k == "action" {
                    continue;
                }
                out.insert(k.clone(), v.clone());
            }
            Value::Object(out)
        }
        other => other.clone(),
    }
}

/// An ordered recording of browser action steps.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Recording {
    /// The ordered sequence of recorded steps.
    pub steps: Vec<RecordedStep>,
    /// The URL that was active when recording started.
    pub created_url: String,
}

impl Recording {
    /// Create a new empty recording, noting the URL at creation time.
    pub fn new(created_url: impl Into<String>) -> Self {
        Self {
            steps: Vec::new(),
            created_url: created_url.into(),
        }
    }

    /// Append a step to the recording.
    pub fn push(&mut self, step: RecordedStep) {
        self.steps.push(step);
    }

    /// Number of recorded steps.
    pub fn len(&self) -> usize {
        self.steps.len()
    }

    /// Whether the recording is empty.
    pub fn is_empty(&self) -> bool {
        self.steps.is_empty()
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════════════
#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn recording_preserves_order() {
        let mut rec = Recording::new("https://example.com");
        let steps = vec![
            RecordedStep {
                intent: "navigate to page".into(),
                action: "navigate".into(),
                args: json!({"url": "https://example.com/form"}),
                selector: None,
                url: "https://example.com".into(),
            },
            RecordedStep {
                intent: "click the email field".into(),
                action: "click".into(),
                args: json!({"ref": "f0e1"}),
                selector: Some("input[name='email']".into()),
                url: "https://example.com/form".into(),
            },
            RecordedStep {
                intent: "type email address".into(),
                action: "type".into(),
                args: json!({"ref": "f0e1", "text": "user@test.com"}),
                selector: Some("input[name='email']".into()),
                url: "https://example.com/form".into(),
            },
        ];
        for s in &steps {
            rec.push(s.clone());
        }

        // Serialize → deserialize round-trips with order intact.
        let json_str = serde_json::to_string(&rec).expect("serialize");
        let deserialized: Recording = serde_json::from_str(&json_str).expect("deserialize");

        assert_eq!(deserialized.steps.len(), 3);
        assert_eq!(deserialized.steps, steps);
        assert_eq!(deserialized.created_url, "https://example.com");
    }

    #[test]
    fn secret_step_records_ref_not_value() {
        // A type action with a secret:NAME reference must store the TOKEN in args,
        // NEVER the resolved plaintext value.
        let plaintext_probe = "SuperS3cretP@ssw0rd!";

        // 1) Direct construction (the step carries the token, not the value).
        let step = RecordedStep {
            intent: "type password".into(),
            action: "type".into(),
            args: json!({"ref": "f0e2", "text": "secret:pw"}),
            selector: Some("input[type='password']".into()),
            url: "https://example.com/login".into(),
        };

        let serialized = serde_json::to_string(&step).expect("serialize");
        assert!(
            serialized.contains("secret:pw"),
            "recording must contain the secret:NAME token; got: {serialized}"
        );
        assert!(
            !serialized.contains(plaintext_probe),
            "recording must NEVER contain the plaintext secret value; got: {serialized}"
        );

        // 2) from_action constructor: given the raw input (pre-resolution), the
        //    step args carry the token, not any resolved value.
        let raw_input = json!({
            "action": "type",
            "ref": "f0e2",
            "text": "secret:pw"
        });
        let step2 = RecordedStep::from_action(
            "type",
            &raw_input,
            Some("input[type='password']".into()),
            "https://example.com/login".into(),
        );
        let serialized2 = serde_json::to_string(&step2).expect("serialize");
        assert!(
            serialized2.contains("secret:pw"),
            "from_action must preserve the secret:NAME token; got: {serialized2}"
        );
        assert!(
            !serialized2.contains(plaintext_probe),
            "from_action must NEVER contain plaintext; got: {serialized2}"
        );
        // The "action" key is stripped (redundant with step.action field).
        assert!(
            !step2.args.get("action").is_some(),
            "action key must be stripped from args"
        );
    }
}
