//! Companion-domain capabilities (registry form): digital companion CRUD,
//! runtime status, shared config, and self-improvement suggestions.
//!
//! These tools let the LLM agent manage the desktop's digital companions on
//! behalf of the user — create/configure/delete companions, inspect their
//! status, and act on self-improvement suggestions generated by the learning
//! subsystem.

use std::sync::Arc;

use schemars::JsonSchema;
use serde::Deserialize;
use serde_json::{Value, json};

use crate::deps::GatewayDeps;
use crate::registry::{Capability, CapabilityMeta, DangerTier, Surface};
use crate::server::ok;

const DEFAULT_SUGGESTION_LIMIT: i64 = 20;

// ── param structs (single source: schema + runtime) ──────────────────────

#[derive(Deserialize, JsonSchema)]
struct CompanionListParams {}

#[derive(Deserialize, JsonSchema)]
struct CompanionGetParams {
    /// The companion id to retrieve (from nomi_companion_list).
    id: String,
}

#[derive(Deserialize, JsonSchema)]
struct CompanionCreateParams {
    /// Display name for the new companion.
    name: String,
    /// Character archetype / seed description. This seeds the companion's
    /// personality and initial system prompt generation.
    character: String,
}

#[derive(Deserialize, JsonSchema)]
struct CompanionUpdateParams {
    /// The companion id to update (from nomi_companion_list).
    id: String,
    /// RFC 7396 merge-patch object. Valid top-level keys: "name" (string),
    /// "character" (string), "persona" (object with "preset"/"custom"),
    /// "model" (object with "provider_id"/"model"),
    /// "appearance" (object — companion window config).
    /// Only provided keys are changed; omitted keys are untouched.
    patch: Value,
}

#[derive(Deserialize, JsonSchema)]
struct CompanionDeleteParams {
    /// The companion id to permanently delete. This removes all associated
    /// data (thread, memories attributed to this companion, figure binding).
    id: String,
}

#[derive(Deserialize, JsonSchema)]
struct CompanionStatusParams {
    /// The companion id. If omitted, returns the default companion's status.
    #[serde(default)]
    id: Option<String>,
}

#[derive(Deserialize, JsonSchema)]
struct CompanionGetConfigParams {}

#[derive(Deserialize, JsonSchema)]
struct CompanionUpdateConfigParams {
    /// RFC 7396 merge-patch object for the shared companion config.
    /// Valid top-level keys: "collect" (object — per-source booleans),
    /// "learn" (object — learning schedule), "default_companion_id" (string),
    /// "bridge_to_memory_dir" (string | null).
    patch: Value,
}

#[derive(Deserialize, JsonSchema)]
struct CompanionListSuggestionsParams {
    /// Filter by status: "new", "accepted", or "dismissed". Omit for all.
    #[serde(default)]
    status: Option<String>,
    /// Maximum number of suggestions to return (default 20, clamped to 1..=100).
    #[serde(default)]
    limit: Option<i64>,
}

#[derive(Deserialize, JsonSchema)]
struct CompanionDecideSuggestionParams {
    /// The suggestion id to act on (from nomi_companion_list_suggestions).
    id: String,
    /// true = accept the suggestion (applies it and awards XP);
    /// false = dismiss it. The decision is idempotent — calling again with
    /// the same id is a no-op.
    accept: bool,
}

// ── handlers ──────────────────────────────────────────────────────────────

async fn list(deps: Arc<GatewayDeps>, _p: CompanionListParams) -> Value {
    let companions = deps.companion_service.list_companions().await;
    ok(companions)
}

async fn get(deps: Arc<GatewayDeps>, p: CompanionGetParams) -> Value {
    match deps.companion_service.get_companion(&p.id).await {
        Ok(companion) => ok(companion),
        Err(e) => json!({ "error": e.to_string() }),
    }
}

async fn create(deps: Arc<GatewayDeps>, p: CompanionCreateParams) -> Value {
    let name = p.name.trim();
    if name.is_empty() {
        return json!({ "error": "missing required field: name" });
    }
    let character = p.character.trim();
    if character.is_empty() {
        return json!({ "error": "missing required field: character" });
    }
    match deps.companion_service.create_companion(name, character).await {
        Ok(companion) => ok(companion),
        Err(e) => json!({ "error": e.to_string() }),
    }
}

async fn update(deps: Arc<GatewayDeps>, p: CompanionUpdateParams) -> Value {
    if !p.patch.is_object() {
        return json!({ "error": "patch must be a JSON object" });
    }
    if p.patch.as_object().map_or(true, |m| m.is_empty()) {
        return json!({ "error": "patch must contain at least one field to update" });
    }
    match deps.companion_service.patch_companion(&p.id, p.patch).await {
        Ok(companion) => ok(companion),
        Err(e) => json!({ "error": e.to_string() }),
    }
}

async fn delete(deps: Arc<GatewayDeps>, p: CompanionDeleteParams) -> Value {
    match deps.companion_service.delete_companion(&p.id).await {
        Ok(()) => json!({ "result": format!("companion {} deleted", p.id) }),
        Err(e) => json!({ "error": e.to_string() }),
    }
}

async fn status(deps: Arc<GatewayDeps>, p: CompanionStatusParams) -> Value {
    let result = match p.id {
        Some(ref id) => deps.companion_service.companion_status(id).await,
        None => deps.companion_service.status().await,
    };
    match result {
        Ok(s) => ok(s),
        Err(e) => json!({ "error": e.to_string() }),
    }
}

async fn get_config(deps: Arc<GatewayDeps>, _p: CompanionGetConfigParams) -> Value {
    let config = deps.companion_service.get_config().await;
    ok(config)
}

async fn update_config(deps: Arc<GatewayDeps>, p: CompanionUpdateConfigParams) -> Value {
    if !p.patch.is_object() {
        return json!({ "error": "patch must be a JSON object" });
    }
    if p.patch.as_object().map_or(true, |m| m.is_empty()) {
        return json!({ "error": "patch must contain at least one field to update" });
    }
    match deps.companion_service.patch_config(p.patch).await {
        Ok(config) => ok(config),
        Err(e) => json!({ "error": e.to_string() }),
    }
}

async fn list_suggestions(deps: Arc<GatewayDeps>, p: CompanionListSuggestionsParams) -> Value {
    let limit = p.limit.unwrap_or(DEFAULT_SUGGESTION_LIMIT).clamp(1, 100);
    match deps
        .companion_service
        .list_suggestions(p.status.as_deref(), limit)
        .await
    {
        Ok(suggestions) => ok(suggestions),
        Err(e) => json!({ "error": e.to_string() }),
    }
}

async fn decide_suggestion(deps: Arc<GatewayDeps>, p: CompanionDecideSuggestionParams) -> Value {
    match deps
        .companion_service
        .decide_suggestion(&p.id, p.accept)
        .await
    {
        Ok(suggestion) => ok(suggestion),
        Err(e) => json!({ "error": e.to_string() }),
    }
}

// ── registration ─────────────────────────────────────────────────────────

/// Register the companion-domain capabilities.
pub(crate) fn register(out: &mut Vec<Capability>) {
    // 1. List companions (read)
    out.push(Capability::new::<CompanionListParams, _, _>(
        CapabilityMeta::new(
            "nomi_companion_list",
            "companion",
            "List all digital companions (id, name, character, model, appearance).",
            DangerTier::Read,
        ),
        |deps, _ctx, p| list(deps, p),
    ));

    // 2. Get companion (read)
    out.push(Capability::new::<CompanionGetParams, _, _>(
        CapabilityMeta::new(
            "nomi_companion_get",
            "companion",
            "Get a single companion's full profile and configuration by id.",
            DangerTier::Read,
        ),
        |deps, _ctx, p| get(deps, p),
    ));

    // 3. Create companion (write)
    out.push(Capability::new::<CompanionCreateParams, _, _>(
        CapabilityMeta::new(
            "nomi_companion_create",
            "companion",
            "Create a new digital companion with a name and character description. The model must be configured separately via nomi_companion_update.",
            DangerTier::Write,
        ),
        |deps, _ctx, p| create(deps, p),
    ));

    // 4. Update companion (write)
    out.push(Capability::new::<CompanionUpdateParams, _, _>(
        CapabilityMeta::new(
            "nomi_companion_update",
            "companion",
            "Partially update a companion's profile (name, character, persona, model, appearance). Pass an RFC 7396 merge-patch object.",
            DangerTier::Write,
        ),
        |deps, _ctx, p| update(deps, p),
    ));

    // 5. Delete companion (destructive, deny on channel)
    out.push(Capability::new::<CompanionDeleteParams, _, _>(
        CapabilityMeta::new(
            "nomi_companion_delete",
            "companion",
            "Permanently delete a companion and all its associated data (thread, figure binding). Irreversible.",
            DangerTier::Destructive,
        )
        .deny_on(&[Surface::Channel]),
        |deps, _ctx, p| delete(deps, p),
    ));

    // 6. Companion status (read)
    out.push(Capability::new::<CompanionStatusParams, _, _>(
        CapabilityMeta::new(
            "nomi_companion_status",
            "companion",
            "Get a companion's runtime status (XP, level, mood, memory counts, suggestion counts, model readiness). Omit id for the default companion.",
            DangerTier::Read,
        ),
        |deps, _ctx, p| status(deps, p),
    ));

    // 7. Get shared config (read)
    out.push(Capability::new::<CompanionGetConfigParams, _, _>(
        CapabilityMeta::new(
            "nomi_companion_get_config",
            "companion",
            "Read the shared companion configuration (collection toggles, learning schedule, default companion id).",
            DangerTier::Read,
        ),
        |deps, _ctx, p| get_config(deps, p),
    ));

    // 8. Update shared config (write)
    out.push(Capability::new::<CompanionUpdateConfigParams, _, _>(
        CapabilityMeta::new(
            "nomi_companion_update_config",
            "companion",
            "Partially update the shared companion configuration (collection toggles, learning schedule, default companion, memory bridge). RFC 7396 merge-patch.",
            DangerTier::Write,
        ),
        |deps, _ctx, p| update_config(deps, p),
    ));

    // 9. List suggestions (read)
    out.push(Capability::new::<CompanionListSuggestionsParams, _, _>(
        CapabilityMeta::new(
            "nomi_companion_list_suggestions",
            "companion",
            "List self-improvement suggestions generated by the companion's learning subsystem. Filter by status (new/accepted/dismissed).",
            DangerTier::Read,
        ),
        |deps, _ctx, p| list_suggestions(deps, p),
    ));

    // 10. Decide suggestion (write)
    out.push(Capability::new::<CompanionDecideSuggestionParams, _, _>(
        CapabilityMeta::new(
            "nomi_companion_decide_suggestion",
            "companion",
            "Accept or dismiss a self-improvement suggestion. Accepting awards XP to all companions. The decision is idempotent.",
            DangerTier::Write,
        ),
        |deps, _ctx, p| decide_suggestion(deps, p),
    ));
}
