//! Access to the bun bytes embedded at build time.
//!
//! Production reads constants emitted by `build.rs` into
//! `$OUT_DIR/bun_meta.rs`. When `NOMIFUN_EMBED_BUN` is unset at build time,
//! `build.rs` emits a stub with `HAS_EMBEDDED_BUN = false`, which makes
//! `resolve_bun()` fall back to `which()` — exactly the pre-embed behavior.

/// Raw compile-time constants generated by `build.rs` into `$OUT_DIR/bun_meta.rs`.
pub(crate) mod consts {
    include!(concat!(env!("OUT_DIR"), "/bun_meta.rs"));
}

/// Indirection trait so tests can inject a fake embedded payload instead
/// of linking the real (potentially 30MB+) compressed blob.
pub trait EmbeddedBun: Send + Sync {
    fn has(&self) -> bool;
    fn blob(&self) -> &'static [u8];
    fn sha256(&self) -> &'static str;
    fn version(&self) -> &'static str;
}

/// Production implementation backed by constants from `bun_meta.rs`.
#[derive(Debug, Default, Clone, Copy)]
pub struct ProductionEmbed;

impl EmbeddedBun for ProductionEmbed {
    fn has(&self) -> bool {
        consts::HAS_EMBEDDED_BUN
    }
    fn blob(&self) -> &'static [u8] {
        consts::BUN_BLOB
    }
    fn sha256(&self) -> &'static str {
        consts::BUN_SHA256
    }
    fn version(&self) -> &'static str {
        consts::BUN_VERSION
    }
}

#[cfg(test)]
pub(crate) struct FakeEmbed {
    pub has: bool,
    pub blob: &'static [u8],
    pub sha256: &'static str,
    pub version: &'static str,
}

#[cfg(test)]
impl EmbeddedBun for FakeEmbed {
    fn has(&self) -> bool {
        self.has
    }
    fn blob(&self) -> &'static [u8] {
        self.blob
    }
    fn sha256(&self) -> &'static str {
        self.sha256
    }
    fn version(&self) -> &'static str {
        self.version
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn production_embed_respects_env_gate() {
        // Unless NOMIFUN_EMBED_BUN=1 at build time, ProductionEmbed reports "no embed".
        assert!(!ProductionEmbed.has());
        assert_eq!(ProductionEmbed.blob(), b"");
    }

    #[test]
    fn fake_embed_returns_injected_values() {
        let fake = FakeEmbed {
            has: true,
            blob: b"hello",
            sha256: "deadbeef",
            version: "9.9.9",
        };
        assert!(fake.has());
        assert_eq!(fake.blob(), b"hello");
        assert_eq!(fake.sha256(), "deadbeef");
        assert_eq!(fake.version(), "9.9.9");
    }
}
