// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnStopReason } from "./TurnStopReason";

/**
 * Data for the `Finish` event.
 */
export type FinishEventData = { session_id: string | null, 
/**
 * Why the turn ended. `None` = the backend did not report (treated as
 * success for back-compat). `EndTurn` = normal completion; `MaxTokens` /
 * `MaxTurnRequests` / `Refusal` / `Cancelled` = the turn did NOT accomplish
 * its goal. AutoWork consults this instead of treating any Finish as done.
 */
stop_reason: TurnStopReason | null, };
