// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for the `SessionAssigned` event.
 */
export type SessionAssignedEventData = { session_id: string, };
