// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for the `Start` event.
 */
export type StartEventData = { session_id: string | null, };
