// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnStopReason } from "./TurnStopReason";

/**
 * Data for the `TurnCompleted` event — aggregate metrics for one turn.
 */
export type TurnCompletedEventData = { 
/**
 * Wall-clock duration of the turn in milliseconds.
 */
elapsed_ms: number, input_tokens: number, output_tokens: number, 
/**
 * Tokens written into the provider prompt cache.
 */
cache_creation_tokens: number,
/**
 * Tokens read back from the provider prompt cache.
 */
cache_read_tokens: number,
/**
 * Current context occupancy (last request's prompt tokens). Gauge numerator.
 */
context_tokens: number, 
/**
 * Effective context budget (engine compaction window). Gauge denominator.
 */
context_window: number, 
/**
 * Why the turn ended (mirrors Finish), for a single self-contained record.
 */
stop_reason: TurnStopReason | null, };
